image: rubenchristoffer/php7_mysql_codeception_composer

# Select what we should cache
cache:
  paths:
    - vendor/

before_script:
  # Print working directory
  - pwd
  # Install all project dependencies
  - composer install
  # Run webserver
  - php -S localhost:8085 --docroot public &>/dev/null&
  # Run mysql
  - service mysql start
  # Create test database
  - mysql -u root -e "CREATE DATABASE idatg2204"
  # Setup test user
  - mysql -u root -e "CREATE USER 'idatg2204'@'%' IDENTIFIED BY 'password';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'idatg2204'@'%';"
  # Create config file
  - echo "<?php  " > config/config_test.php
  - echo "set_include_path('$(pwd)');" >> config/config_test.php
  - echo "

    const config = array(
    'db_driver' => 'mysql',
    'db_host' => 'localhost',
    'db_port' => '3306',
    'db_username' => 'root',
    'db_password' => '',
    'db_name' => 'idatg2204',
    'db_charset' => 'utf8mb4'
    );" >> config/config_test.php
  # Print config file
  - cat config/config_test.php
  # Copy template file for tests
  - cp tests/api.suite_template.yml tests/api.suite.yml
  - cp tests/unit.suite_template.yml tests/unit.suite.yml
  # List files in tests directory
  - ls tests/
  # Setup apache2 document root
  - cat /etc/apache2/sites-enabled/000-default.conf | sed -e "s|/var/www/html|$(pwd)/public|" > /etc/apache2/sites-enabled/test.conf
  - rm /etc/apache2/sites-enabled/000-default.conf
  - cat /etc/apache2/sites-enabled/test.conf
  # Update apache2.conf
  - cat /etc/apache2/apache2.conf | sed -e "s|/var/www/|$(pwd)|" | sed -e "s|AllowOverride None|AllowOverride All|" > /etc/apache2/apache2.newconf
  - mv /etc/apache2/apache2.newconf /etc/apache2/apache2.conf
  - cat /etc/apache2/apache2.conf
  # Enable rewriting
  - a2enmod rewrite
  # Start apache2
  - service apache2 start
  # Set permissions
  - chmod -R 777 *
  # Test web server
  - curl http://localhost/rest/ghghh

# Test
test:
  script:
    - vendor/bin/codecept run
  after_script:
    - cat tests/_output/*